tip:
  - class: TipBadge
    attributes:
      result: correct
      icon: 'fa-bullseye'
      levels:
        - achievement: 1
          color: bronze
          score: 2400
        - achievement: 5
          color: silver
          score: 4400
        - achievement: 10
          color: gold
          score: 6400
        - achievement: 15
          color: platinum
          score: 8400
  - class: TipConsecutiveBadge
    attributes:
      result: correct
      icon: 'fa-rocket'
      levels:
        - achievement: 2
          color: bronze
          score: 2600
        - achievement: 3
          color: silver
          score: 4600
        - achievement: 4
          color: gold
          score: 6600
        - achievement: 5
          color: platinum
          score: 8600
  - class: TipCorrectTendencyBadge
    attributes:
      icon: 'fa-star-half-o'
      levels:
        - achievement: 1
          color: bronze
          score: 2000
        - achievement: 8
          color: silver
          score: 4000
        - achievement: 16
          color: gold
          score: 6000
        - achievement: 24
          color: platinum
          score: 8000
  - class: TipConsecutiveCorrectTendencyBadge
    attributes:
      icon: 'fa-fighter-jet'
      levels:
        - achievement: 2
          color: bronze
          score: 2200
        - achievement: 5
          color: silver
          score: 4200
        - achievement: 8
          color: gold
          score: 6200
        - achievement: 12
          color: platinum
          score: 8200
  - class: TipBadge
    attributes:
      result: incorrect
      icon: 'fa-bug'
      levels:
        - achievement: 1
          color: bronze
          score: -6400
        - achievement: 10
          color: silver
          score: -6300
        - achievement: 20
          color: gold
          score: -2400
        - achievement: 30
          color: platinum
          score: -2300
  - class: TipConsecutiveBadge
    attributes:
      result: incorrect
      icon: 'fa-medkit'
      levels:
        - achievement: 2
          color: bronze
          score: -7400
        - achievement: 4
          color: silver
          score: -7300
        - achievement: 6
          color: gold
          score: -3400
        - achievement: 8
          color: platinum
          score: -3300
  - class: TipMissedBadge
    attributes:
      icon: 'fa-globe'
      levels:
        - achievement: 1
          color: bronze
          score: -8400
        - achievement: 2
          color: silver
          score: -8300
        - achievement: 4
          color: gold
          score: -4400
        - achievement: 8
          color: platinum
          score: -4300
  - class: TipConsecutiveMissedBadge
    attributes:
      icon: 'fa-ambulance'
      levels:
        - achievement: 2
          color: bronze
          score: -9400
        - achievement: 3
          color: silver
          score: -9300
        - achievement: 4
          color: gold
          score: -5400
        - achievement: 5
          color: platinum
          score: -5300
  - class: TipChampionMissedBadge
    attributes:
      icon: 'fa-eye-slash'
      levels:
        - achievement: 1
          color: platinum
          score: -10000
comment:
  - class: CommentCreatedBadge
    attributes:
      icon: 'fa-comments-o'
      levels:
        - achievement: 1
          color: bronze
          score: 1100
        - achievement: 8
          color: silver
          score: 1200
        - achievement: 16
          color: gold
          score: 1300
        - achievement: 24
          color: platinum
          score: 1400
  - class: CommentConsecutiveCreatedBadge
    attributes:
      icon: 'fa-bullhorn'
      levels:
        - achievement: 3
          color: bronze
          score: -300
        - achievement: 5
          color: silver
          score: -200
        - achievement: 8
          color: gold
          score: -100