- author: Bobby Robson
  content: We didn’t underestimate them. They were just a lot better than we thought.
- author: Pelé
  content: A penalty is a cowardly way to score.
- author: Jean-Paul Charles Aymard Sartre
  content: In football everything is complicated by the presence of the opposite team.
- author: Aleksander Ristic
  content: Bei manchen Spielern fehlt etwas, deshalb spielen sie auch bei mir und nicht in Barcelona.
- author: Reiner Calmund
  content: Bevor wir für einen Torwart 15 bis 20 Millionen Mark bezahlen, stelle ich mich selbst ins Tor.
- author: Thomas Helmer
  content: Da muß dann auch mal einer die Hand ins Heft nehmen.
- author: Bela Rethy
  content: Das da vorn, was aussieht wie eine Klobürste, ist Valderrama.
- author: Jürgen Klinsmann
  content: Das sind Gefühle, wo man schwer beschreiben kann.
- author: Thomas Strunz
  content: Das Schönste an Stuttgart ist die Autobahn nach München.
- author: Felix Magath
  content: Das war europäische Weltklasse!
- author: Gyula Lorant
  content: Der Ball ist rund. Wäre er eckig, wäre er ja ein Würfel.
- author: Beni Turnher
  content: Der Rasen sieht alt und gebraucht aus, irgendwie erinnert er mich an die Kleider der Kelly Family.
- author: Gerd Rubenbauer
  content: Die Achillesferse von Bobic ist die rechte Schulter.
- author: Oliver Kahn
  content: Die Fans müssen wissen, daß ich kein Clown bin.
- author: Fritz Walter
  content: Die Sanitäter haben mir sofort eine Invasion gelegt.
- author: Gerhard Delling
  content: Die Luft, die nie drin war, ist raus aus dem Spiel.
- author: Franz Beckenbauer
  content: Die Schweden sind keine Holländer - das hat man ganz genau gesehen.
- author: Gerd Rubenbauer
  content: Diese "Ruuudi-Ruuudi"-Rufe hat es vorher nur für Uwe Seeler gegeben.
- author: Max Merkel
  content: Eine Straßenbahn hat mehr Anhänger als Uerdingen.
- author: Lothar Matthäus
  content: Es ist wichtig, daß man neunzig Minuten mit voller Konzentration an das nächste Spiel denkt.
- author: Franz Beckenbauer
  content: Abseits ist, wenn der Schiedsrichter pfeift.
- author: Lothar Matthäus
  content: Wir dürfen jetzt nur nicht den Sand in den Kopf stecken.
- author: Werner Hansch
  content: Nein, liebe Zuschauer, das ist keine Zeitlupe, der läuft wirklich so langsam.
- author: Johannes B. Kerner
  content: Was nützt die schönste Viererkette, wenn sie anderweitig unterwegs ist.
- author: Andreas Möller
  content: Mailand oder Madrid - Hauptsache Italien!
- author: Jürgen Klinsmann
  content: Der Rizitelli und ich sind schon ein tolles Trio, ....äh Quartett.
- author: Aleksander Ristic
  content: Wenn man ein 0:2 kassiert, dann ist ein 1:1 nicht mehr möglich.
- author: Usain Bolt
  content: I really want to try soccer after I retire because I've watched football over the years and I think I could be a good contender.
- author: Lady Gaga
  content: I want kids. I want a soccer team, and I want a husband.
- author: Andreas Möller
  content: Mein Problem ist, dass ich immer sehr selbstkritisch bin, auch mir selbst gegenüber.
- author: Roy Präger
  content: Jetzt kommt es darauf an, dass wir die entscheidenden Punkte gegen den Nicht-Abstieg sammeln!
- author: Rudi Völler
  content: Zu 50 Prozent stehen wir im Viertelfinale, aber die halbe Miete ist das noch lange nicht!
- author: Harald Schmidt
  content: Jürgen Klinsmann ist inzwischen 694 Minuten ohne Tor. Das hat vor ihm, glaube ich, nur Sepp Maier geschafft.
- author: Jörg Dahlmann
  content: Da geht er, ein großer Spieler. Ein Mann wie Steffi Graf.
- author: Werner Hansch
  content: Wer hinten so offen ist, kann nicht ganz dicht sein.
- author: Johannes B. Kerner
  content: Es ist schon an der Grenze zum Genuss, den Koreanern zuzusehen.
- author: Paul Breitner
  content: Sie sollen nicht glauben, das sie Brasilianer sind, nur weil sie aus Brasilien kommen.
- author: Gerhard Delling
  content: Da geht er durch die Beine, knapp an den Beinen vorbei, durch die Arme.
- author: Marcel Reif
  content: Je länger das Spiel dauert, desto weniger Zeit bleibt.
- author: Gerard Houllier
  content: You can’t say my team aren’t winners. They’ve proved that by finishing fourth, third and second in the last three years
- author: Gary Lineker
  content: There is no in between- you’re either good or bad. We were in between.
- author: Ulf Kirstens
  content: "Wenn bei einem Auswärtsspiel keiner ruft: 'Kirsten, du Arschloch', dann weiß ich genau, dass ich schlecht bin."
- author: George Best
  content: Ich habe viel von meinem Geld für Alkohol, Weiber und schnelle Autos ausgegeben. Den Rest habe ich einfach verprasst
- author: Werner Hansch
  content: Ja, Statistiken. Aber welche Statistik stimmt schon? Nach der Statistik ist jeder 4. Mensch ein Chinese, aber hier spielt gar kein Chinese mit.
- author: Marcel Reif
  content: Wenn Sie dieses Spiel atemberaubend finden, haben sie es an den Bronchien.
- author: Heribert Faßbender
  content: "Und jetzt skandieren die Fans wieder: Türkiye, Türkiye. Was so viel heißt wie Türkei, Türkei."
- author: Paul Breitner
  content: Ich habe nur immer meine Finger in Wunden gelegt, die sonst unter den Tisch gekehrt worden wären.
- author: Mike Gray
  content: Well Kerry, you’re 19 and you’re a lot older than a lot of people younger than yourself.
- author: Jose Mourinho
  content: Please don’t call me arrogant, but I’m European champion and I think I’m a special one.
- author: Rod Stewart
  content: I'm a rock star because I couldn't be a soccer star.